// <auto-generated />
namespace AssessmentMVC_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MovieMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202501021732312_Movie Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
